version: '3.2'
services:
    proxy:
        image: nginx:latest
        volumes:
            - type: bind
              source: ./proxy    
              target: /etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    web01:
        image: nginx:latest
        volumes:
            - type: bind
              source: ./web1.html
              target: /usr/share/nginx/html/index.html
                
            
    web02:
        image: nginx:latest
        volumes:
            - type: bind
              source: ./web2.html
              target: /usr/share/nginx/html/index.html
        
